server:
  port: 8500
spring:
  application:
    name: wishlist-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: http://localhost:9092
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://config-service:8888

management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"
