server:
  port: 8500
spring:
  application:
    name: wishlist-service
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://localhost:8888

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

service:
  product:
    domain: ${service.coupon.domain}