server:
  port: 8500

spring:
  application:
    name: wishlist-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: http://localhost:9092
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://localhost:8888


management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"

service:
  product:
    domain: http://localhost:5000
  store:
    domain : http://loalhost:6000
