name: develop deployment
on:
  push:
    branches:
      - 'develop'
jobs:
  deployment:
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DEV_DOCKER_ID }}
          password: ${{ secrets.DEV_DOCKER_PW }}
      - name: deploy
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: nowgnas/bb:wishlist
